apiVersion: v1
kind: Secret
metadata:
  name: security-app-db
  namespace: restaurant
  annotations:
    avp.kubernetes.io/path: "restaurant-secrets"
  labels:
    app: security
type: Opaque
stringData:
  rootUserName: <security_db_root_user>
  rootUserPass: <security_db_root_pass>
