apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: restaurant
  labels:
    app: notification
spec:
  selector:
    app: notification
  ports:
  -
    name: tls-notification
    protocol: TCP
    port: 5052
    targetPort: 5052
